import React, { useEffect, useMemo, useRef, useState } from "react";
import { supabase } from "./lib/supabaseClient";

const characterOptions = [
  { id: "bear", es: "Osita Koda", en: "Koda Bear", emoji: "🧸" },
  { id: "girl", es: "Niña Koda", en: "Koda Girl", emoji: "👧" },
  { id: "boy", es: "Niño Koda", en: "Koda Boy", emoji: "👦" },
];

const intentions = {
  es: [
    "Explorar emoción",
    "Tranquilizar",
    "Validar miedo",
    "Validar tristeza",
    "Romper el hielo",
    "Animar",
    "Ansiedad",
    "Autismo / Sensibilidad",
  ],
  en: [
    "Explore emotion",
    "Calm down",
    "Validate fear",
    "Validate sadness",
    "Break the ice",
    "Encourage",
    "Anxiety",
    "Autism / Sensory support",
  ],
};

const emptyProfessionalProfile = {
  name: "",
  email: "",
  specialty: "",
  country: "",
  practiceType: "",
  preferredLanguage: "es",
};

function cleanForSpeech(text = "") {
  return text
    .replace(/[\u{1F300}-\u{1FAFF}]/gu, "")
    .replace(/[#*_`~>|[\]{}]/g, "")
    .replace(/\b(emoji|emoticon|corazón rojo|red heart|heart emoji)\b/gi, "")
    .replace(/\s+/g, " ")
    .trim();
}

function mapDatabaseRecord(record, language = "es") {
  return {
    id: record.id,
    childName: record.child_name || "",
    age: record.age || "",
    language: record.language || language,
    character: record.character || "",
    intention: record.intention || "",
    therapistText: record.therapist_text || "",
    adaptedText: record.adapted_text || "",
    notes: record.notes || "",
    dateISO: record.created_at,
    dateLabel: new Date(record.created_at).toLocaleString(
      language === "es" ? "es-MX" : "en-US",
      {
        dateStyle: "medium",
        timeStyle: "short",
      }
    ),
  };
}

function formatRecord(record, language = "es") {
  if (language === "en") {
    return `Koda Session Record

Professional: ${record.professionalName || "N/A"}
Child / Alias: ${record.childName || "N/A"}
Age: ${record.age || "N/A"}
Date: ${record.dateLabel || "N/A"}
Language: ${record.language || "N/A"}
Character: ${record.character || "N/A"}
Therapeutic intention: ${record.intention || "N/A"}

Professional phrase:
${record.therapistText || "N/A"}

Koda response:
${record.adaptedText || "N/A"}

Professional notes:
${record.notes || "No notes"}

Generated by Koda.`;
  }

  return `Registro de sesión Koda

Profesional: ${record.professionalName || "N/A"}
Niño / Alias: ${record.childName || "N/A"}
Edad: ${record.age || "N/A"}
Fecha: ${record.dateLabel || "N/A"}
Idioma: ${record.language || "N/A"}
Personaje: ${record.character || "N/A"}
Intención: ${record.intention || "N/A"}

Frase del profesional:
${record.therapistText || "N/A"}

Respuesta de Koda:
${record.adaptedText || "N/A"}

Notas del profesional:
${record.notes || "Sin notas"}

Generado por Koda.`;
}

export default function KodaMvpEngine() {
  const [screen, setScreen] = useState("welcome");
  const [authMode, setAuthMode] = useState("signup");
  const [language, setLanguage] = useState("es");

  const [authUser, setAuthUser] = useState(null);
  const [isAuthLoading, setIsAuthLoading] = useState(true);
  const [password, setPassword] = useState("");

  const [professionalProfile, setProfessionalProfile] = useState(
    emptyProfessionalProfile
  );
  const [isProfessionalRegistered, setIsProfessionalRegistered] =
    useState(false);

  const [records, setRecords] = useState([]);
  const [sessionNotes, setSessionNotes] = useState("");

  const [childName, setChildName] = useState("Sofi");
  const [age, setAge] = useState("7");
  const [characterId, setCharacterId] = useState("bear");
  const [intention, setIntention] = useState("Explorar emoción");
  const [therapistText, setTherapistText] = useState(
    "¿Puedes contarme qué pasó cuando tu papá te gritó?"
  );
  const [adaptedText, setAdaptedText] = useState("");
  const [isWorking, setIsWorking] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [statusMessage, setStatusMessage] = useState("Listo");
  const [lastSavedMessage, setLastSavedMessage] = useState("");

  const audioRef = useRef(null);

  const character = useMemo(() => {
    return (
      characterOptions.find((item) => item.id === characterId) ||
      characterOptions[0]
    );
  }, [characterId]);

  const t = {
    es: {
      start: "Crear perfil profesional",
      login: "Ya tengo perfil",
      appSubtitle: "Un puente emocional entre el profesional y el niño.",
      appSupport: "Apoya, comprende y crece juntos.",
      audience:
        "Para psicólogos, terapeutas, médicos, psiquiatras infantiles y profesionales del desarrollo infantil",

      registerTitle: "Crear perfil profesional",
      loginTitle: "Iniciar sesión",
      registerSubtitle:
        "Crea una cuenta para guardar tus registros ligeros de Koda en tu base de datos.",
      loginSubtitle:
        "Entra con tu correo y contraseña para continuar trabajando con Koda.",
      fullName: "Nombre completo",
      email: "Correo",
      password: "Contraseña",
      specialty: "Especialidad",
      country: "País",
      practiceType: "Tipo de práctica",
      preferredLanguage: "Idioma preferido",
      saveProfile: "Crear cuenta",
      loginButton: "Entrar",
      updateProfile: "Actualizar perfil",
      profileSaved: "Perfil creado correctamente.",
      requiredProfile: "Nombre y correo son obligatorios.",
      alreadyHaveProfile: "Ya tengo perfil",
      needCreateProfile: "Crear perfil nuevo",
      minPassword: "La contraseña debe tener al menos 6 caracteres.",
      emailPasswordRequired: "Escribe correo y contraseña.",
      loginError: "No se pudo iniciar sesión. Revisa correo y contraseña.",
      signOut: "Cerrar sesión",

      dashboardTitle: "Bienvenido a Koda",
      dashboardSubtitle:
        "Adapta frases profesionales a lenguaje infantil y guarda registros ligeros, exportables y ordenados.",
      newSession: "Nueva sesión",
      continueSession: "Entrar al motor emocional",
      demoMode: "Modo demo para promoción",
      language: "Idioma",
      childName: "Nombre o alias del niño",
      age: "Edad",
      character: "Personaje",
      intention: "Intención",
      therapistPhrase: "Frase del profesional",
      placeholder: "Escribe aquí lo que quieres que Koda transforme...",
      talk: "Hablar con Koda",
      stop: "Detener",
      back: "Volver",
      kodaWouldSay: "Koda diría:",
      empty: "Aquí aparecerá la frase adaptada para el niño.",
      safety:
        "Koda no diagnostica, no trata, no prescribe y no sustituye al profesional de salud, terapia o educación infantil. Solo apoya la adaptación del lenguaje.",
      quick: "Datos rápidos",
      engine: "Motor emocional",
      ready: "Listo",
      thinking: "Koda está pensando",
      generatingVoice: "Generando voz",
      speaking: "Hablando",
      premiumPending: "Voz premium pendiente",
      error: "Error",

      feature1Title: "Adaptación de lenguaje",
      feature1Text: "Convierte frases clínicas o profesionales en lenguaje infantil.",
      feature2Title: "Bilingüe",
      feature2Text: "Funciona en español e inglés desde el inicio.",
      feature3Title: "Voz premium",
      feature3Text: "Lista para ElevenLabs cuando activemos el plan.",
      savedRecords: "Registros guardados",
      profileTitle: "Perfil profesional",

      notes: "Notas breves del profesional",
      notesPlaceholder: "Opcional: observaciones breves de la sesión...",
      saveRecord: "Guardar registro",
      copySummary: "Copiar resumen",
      downloadSummary: "Descargar resumen",
      recordSaved: "Registro guardado.",
      noAdaptedText: "Primero genera una respuesta de Koda.",
      historyEmpty: "Todavía no hay registros guardados.",
      deleteRecord: "Eliminar",
      clearHistory: "Borrar historial",
      exportInfo:
        "Koda guarda registros ligeros. Los documentos completos quedan en Drive, nube o sistema clínico del profesional.",
      mustLogin:
        "Inicia sesión para guardar registros en tu cuenta profesional.",
      copied: "Copiado.",
      copyError: "No se pudo copiar automáticamente.",
      loading: "Cargando...",
    },
    en: {
      start: "Create professional profile",
      login: "I already have a profile",
      appSubtitle: "An emotional bridge between professional and child.",
      appSupport: "Support, understand, and grow together.",
      audience:
        "For psychologists, therapists, physicians, child psychiatrists, and child development professionals",

      registerTitle: "Create professional profile",
      loginTitle: "Sign in",
      registerSubtitle:
        "Create an account to save your lightweight Koda records in your database.",
      loginSubtitle:
        "Sign in with your email and password to keep working with Koda.",
      fullName: "Full name",
      email: "Email",
      password: "Password",
      specialty: "Specialty",
      country: "Country",
      practiceType: "Practice type",
      preferredLanguage: "Preferred language",
      saveProfile: "Create account",
      loginButton: "Sign in",
      updateProfile: "Update profile",
      profileSaved: "Profile created successfully.",
      requiredProfile: "Name and email are required.",
      alreadyHaveProfile: "I already have a profile",
      needCreateProfile: "Create new profile",
      minPassword: "Password must be at least 6 characters.",
      emailPasswordRequired: "Enter email and password.",
      loginError: "Could not sign in. Check email and password.",
      signOut: "Sign out",

      dashboardTitle: "Welcome to Koda",
      dashboardSubtitle:
        "Adapt professional phrases into child-friendly language and save lightweight, exportable records.",
      newSession: "New session",
      continueSession: "Open emotional engine",
      demoMode: "Demo mode for promotion",
      language: "Language",
      childName: "Child name or alias",
      age: "Age",
      character: "Character",
      intention: "Intention",
      therapistPhrase: "Professional phrase",
      placeholder: "Write here what you want Koda to transform...",
      talk: "Talk with Koda",
      stop: "Stop",
      back: "Back",
      kodaWouldSay: "Koda would say:",
      empty: "The adapted phrase for the child will appear here.",
      safety:
        "Koda does not diagnose, treat, prescribe, or replace health, therapy, or child education professionals. It only supports language adaptation.",
      quick: "Quick info",
      engine: "Emotional engine",
      ready: "Ready",
      thinking: "Koda is thinking",
      generatingVoice: "Generating voice",
      speaking: "Speaking",
      premiumPending: "Premium voice pending",
      error: "Error",

      feature1Title: "Language adaptation",
      feature1Text: "Turns clinical or professional phrases into child-friendly language.",
      feature2Title: "Bilingual",
      feature2Text: "Built in Spanish and English from the start.",
      feature3Title: "Premium voice",
      feature3Text: "Ready for ElevenLabs once the plan is activated.",
      savedRecords: "Saved records",
      profileTitle: "Professional profile",

      notes: "Brief professional notes",
      notesPlaceholder: "Optional: brief session observations...",
      saveRecord: "Save record",
      copySummary: "Copy summary",
      downloadSummary: "Download summary",
      recordSaved: "Record saved.",
      noAdaptedText: "Generate a Koda response first.",
      historyEmpty: "No records saved yet.",
      deleteRecord: "Delete",
      clearHistory: "Clear history",
      exportInfo:
        "Koda stores lightweight records. Full documents stay in Drive, cloud storage, or the professional’s own system.",
      mustLogin: "Sign in to save records in your professional account.",
      copied: "Copied.",
      copyError: "Could not copy automatically.",
      loading: "Loading...",
    },
  }[language];

  useEffect(() => {
    let mounted = true;

    async function initAuth() {
      const {
        data: { session },
      } = await supabase.auth.getSession();

      if (!mounted) return;

      if (session?.user) {
        setAuthUser(session.user);
        setIsProfessionalRegistered(true);
        await loadProfessionalData(session.user.id);
      }

      setIsAuthLoading(false);
    }

    initAuth();

    const {
      data: { subscription },
    } = supabase.auth.onAuthStateChange(async (event, session) => {
      if (!mounted) return;

      if (session?.user) {
        setAuthUser(session.user);
        setIsProfessionalRegistered(true);
        await loadProfessionalData(session.user.id);
      }

      if (event === "SIGNED_OUT") {
        setAuthUser(null);
        setIsProfessionalRegistered(false);
        setProfessionalProfile(emptyProfessionalProfile);
        setRecords([]);
        setScreen("welcome");
      }
    });

    return () => {
      mounted = false;
      subscription?.unsubscribe?.();
    };
  }, []);

  function stopAudio() {
    if (audioRef.current) {
      audioRef.current.pause();
      audioRef.current.currentTime = 0;
      audioRef.current = null;
    }

    window.speechSynthesis?.cancel?.();
    setIsSpeaking(false);
    setStatusMessage(language === "es" ? "Listo" : "Ready");
  }

  async function handleLanguageChange(newLanguage) {
    stopAudio();
    setLanguage(newLanguage);
    setAdaptedText("");
    setLastSavedMessage("");
    setStatusMessage(newLanguage === "es" ? "Listo" : "Ready");

    setProfessionalProfile((current) => ({
      ...current,
      preferredLanguage: newLanguage,
    }));

    if (authUser) {
      await supabase
        .from("profiles")
        .update({
          preferred_language: newLanguage,
          updated_at: new Date().toISOString(),
        })
        .eq("id", authUser.id);
    }

    if (newLanguage === "es") {
      setIntention("Explorar emoción");
      setTherapistText("¿Puedes contarme qué pasó cuando tu papá te gritó?");
    } else {
      setIntention("Explore emotion");
      setTherapistText("Can you tell me what happened when your dad yelled?");
    }
  }

  async function loadProfessionalData(userId) {
    const { data: profile } = await supabase
      .from("profiles")
      .select("*")
      .eq("id", userId)
      .single();

    const preferredLanguage = profile?.preferred_language || language || "es";

    if (profile) {
      setProfessionalProfile({
        name: profile.name || "",
        email: profile.email || "",
        specialty: profile.specialty || "",
        country: profile.country || "",
        practiceType: profile.practice_type || "",
        preferredLanguage,
      });

      setLanguage(preferredLanguage);
    }

    const { data: savedRecords } = await supabase
      .from("session_records")
      .select("*")
      .eq("user_id", userId)
      .order("created_at", { ascending: false });

    setRecords(
      savedRecords?.map((record) =>
        mapDatabaseRecord(record, preferredLanguage)
      ) || []
    );
  }

  async function saveProfessionalProfile() {
    try {
      setLastSavedMessage("");

      if (
        !professionalProfile.name.trim() ||
        !professionalProfile.email.trim()
      ) {
        setLastSavedMessage(t.requiredProfile);
        return;
      }

      if (!password || password.length < 6) {
        setLastSavedMessage(t.minPassword);
        return;
      }

      const profileData = {
        name: professionalProfile.name.trim(),
        email: professionalProfile.email.trim(),
        specialty: professionalProfile.specialty || "",
        country: professionalProfile.country || "",
        practice_type: professionalProfile.practiceType || "",
        preferred_language: language,
      };

      const { data, error } = await supabase.auth.signUp({
        email: profileData.email,
        password,
        options: {
          data: profileData,
        },
      });

      if (error) throw error;

      if (!data.session) {
        setLastSavedMessage(
          language === "es"
            ? "Cuenta creada. Revisa tu correo para confirmar el acceso."
            : "Account created. Check your email to confirm access."
        );
        return;
      }

      const userId = data.user.id;

      const { error: profileError } = await supabase.from("profiles").upsert({
        id: userId,
        ...profileData,
        updated_at: new Date().toISOString(),
      });

      if (profileError) throw profileError;

      setAuthUser(data.user);
      setIsProfessionalRegistered(true);
      setPassword("");
      setLastSavedMessage(t.profileSaved);

      await loadProfessionalData(userId);
      setScreen("dashboard");
    } catch (error) {
      console.error("KODA REGISTER ERROR:", error);
      setLastSavedMessage(
        error.message ||
          (language === "es"
            ? "Error al crear cuenta."
            : "Error creating account.")
      );
    }
  }

  async function loginProfessional() {
    try {
      setLastSavedMessage("");

      if (!professionalProfile.email.trim() || !password) {
        setLastSavedMessage(t.emailPasswordRequired);
        return;
      }

      const { data, error } = await supabase.auth.signInWithPassword({
        email: professionalProfile.email.trim(),
        password,
      });

      if (error) throw error;

      setAuthUser(data.user);
      setIsProfessionalRegistered(true);
      setPassword("");

      await loadProfessionalData(data.user.id);
      setScreen("dashboard");
    } catch (error) {
      console.error("KODA LOGIN ERROR:", error);
      setLastSavedMessage(t.loginError);
    }
  }

  async function updateProfessionalProfile() {
    try {
      if (!authUser) {
        setLastSavedMessage(t.mustLogin);
        return;
      }

      if (
        !professionalProfile.name.trim() ||
        !professionalProfile.email.trim()
      ) {
        setLastSavedMessage(t.requiredProfile);
        return;
      }

      const profileData = {
        id: authUser.id,
        email: professionalProfile.email.trim(),
        name: professionalProfile.name.trim(),
        specialty: professionalProfile.specialty || "",
        country: professionalProfile.country || "",
        practice_type: professionalProfile.practiceType || "",
        preferred_language: language,
        updated_at: new Date().toISOString(),
      };

      const { error } = await supabase.from("profiles").upsert(profileData);

      if (error) throw error;

      setLastSavedMessage(
        language === "es"
          ? "Perfil actualizado correctamente."
          : "Profile updated successfully."
      );
      setScreen("dashboard");
    } catch (error) {
      console.error("KODA PROFILE UPDATE ERROR:", error);
      setLastSavedMessage(error.message || "Error");
    }
  }

  async function signOutProfessional() {
    stopAudio();
    await supabase.auth.signOut();
  }

  async function adaptWithKoda() {
    const cleanText = therapistText.trim();

    if (!cleanText) {
      throw new Error(
        language === "es"
          ? "Escribe una frase del profesional."
          : "Write a professional phrase."
      );
    }

    const response = await fetch("/api/adapt", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        text: cleanText,
        childName,
        age,
        language,
        intention,
        character: language === "es" ? character.es : character.en,
      }),
    });

    const rawBody = await response.text();

    if (!response.ok) {
      throw new Error(`API ERROR ${response.status}: ${rawBody}`);
    }

    let data;

    try {
      data = JSON.parse(rawBody);
    } catch {
      throw new Error(`Respuesta no JSON: ${rawBody}`);
    }

    if (!data.adaptedText) {
      throw new Error(`La API no regresó adaptedText: ${rawBody}`);
    }

    return cleanForSpeech(data.adaptedText);
  }

  async function speakWithKoda(textToSpeak) {
    const cleanText = cleanForSpeech(textToSpeak);

    if (!cleanText) {
      throw new Error(
        language === "es"
          ? "No hay texto para reproducir."
          : "There is no text to play."
      );
    }

    const response = await fetch("/api/speak", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        text: cleanText,
        language,
      }),
    });

    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`VOICE API ERROR ${response.status}: ${errorBody}`);
    }

    const audioBlob = await response.blob();

    if (!audioBlob || audioBlob.size === 0) {
      throw new Error(
        language === "es"
          ? "ElevenLabs regresó audio vacío."
          : "ElevenLabs returned empty audio."
      );
    }

    const audioUrl = URL.createObjectURL(audioBlob);
    const audio = new Audio(audioUrl);

    audioRef.current = audio;

    audio.onplay = () => {
      setIsSpeaking(true);
      setStatusMessage(t.speaking);
    };

    audio.onended = () => {
      setIsSpeaking(false);
      setStatusMessage(t.ready);
      URL.revokeObjectURL(audioUrl);
    };

    audio.onerror = () => {
      setIsSpeaking(false);
      setStatusMessage(t.error);
      URL.revokeObjectURL(audioUrl);
    };

    await audio.play();
  }

  async function handleTalkWithKoda() {
    try {
      stopAudio();
      setIsWorking(true);
      setAdaptedText("");
      setLastSavedMessage("");
      setStatusMessage(t.thinking);

      const result = await adaptWithKoda();

      setAdaptedText(result);
      setStatusMessage(t.generatingVoice);

      try {
        await speakWithKoda(result);
      } catch (voiceError) {
        console.warn("KODA VOICE WARNING:", voiceError);
        setIsSpeaking(false);
        setStatusMessage(t.premiumPending);
      }

      setIsWorking(false);
    } catch (error) {
      console.error("KODA ERROR:", error);

      setIsWorking(false);
      setIsSpeaking(false);
      setStatusMessage(t.error);

      setAdaptedText(
        language === "es"
          ? `ERROR REAL: ${error.message}`
          : `REAL ERROR: ${error.message}`
      );
    }
  }

  function createCurrentRecord() {
    const now = new Date();

    return {
      id: `${Date.now()}`,
      professionalName: professionalProfile.name,
      professionalEmail: professionalProfile.email,
      childName,
      age,
      language,
      character: language === "es" ? character.es : character.en,
      intention,
      therapistText,
      adaptedText,
      notes: sessionNotes,
      dateISO: now.toISOString(),
      dateLabel: now.toLocaleString(language === "es" ? "es-MX" : "en-US", {
        dateStyle: "medium",
        timeStyle: "short",
      }),
    };
  }

  async function saveSessionRecord() {
    try {
      setLastSavedMessage("");

      if (!authUser) {
        setLastSavedMessage(t.mustLogin);
        setAuthMode("login");
        setScreen("register");
        return;
      }

      if (
        !adaptedText ||
        adaptedText.startsWith("ERROR") ||
        adaptedText.startsWith("REAL ERROR")
      ) {
        setLastSavedMessage(t.noAdaptedText);
        return;
      }

      const { data, error } = await supabase
        .from("session_records")
        .insert({
          user_id: authUser.id,
          child_name: childName,
          age,
          language,
          character: language === "es" ? character.es : character.en,
          intention,
          therapist_text: therapistText,
          adapted_text: adaptedText,
          notes: sessionNotes,
        })
        .select("*")
        .single();

      if (error) throw error;

      const mappedRecord = mapDatabaseRecord(data, language);

      setRecords([mappedRecord, ...records]);
      setLastSavedMessage(t.recordSaved);
    } catch (error) {
      console.error("KODA SAVE RECORD ERROR:", error);
      setLastSavedMessage(error.message || "Error");
    }
  }

  async function copyText(text) {
    try {
      await navigator.clipboard.writeText(text);
      setLastSavedMessage(t.copied);
    } catch {
      setLastSavedMessage(t.copyError);
    }
  }

  function downloadTextFile(text, filename = "koda-registro.txt") {
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");

    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    link.remove();

    URL.revokeObjectURL(url);
  }

  function copyCurrentSummary() {
    if (
      !adaptedText ||
      adaptedText.startsWith("ERROR") ||
      adaptedText.startsWith("REAL ERROR")
    ) {
      setLastSavedMessage(t.noAdaptedText);
      return;
    }

    copyText(formatRecord(createCurrentRecord(), language));
  }

  function downloadCurrentSummary() {
    if (
      !adaptedText ||
      adaptedText.startsWith("ERROR") ||
      adaptedText.startsWith("REAL ERROR")
    ) {
      setLastSavedMessage(t.noAdaptedText);
      return;
    }

    const safeName = (childName || "koda")
      .toLowerCase()
      .replace(/[^a-z0-9áéíóúñ]+/gi, "-")
      .replace(/^-|-$/g, "");

    downloadTextFile(
      formatRecord(createCurrentRecord(), language),
      `koda-${safeName || "registro"}-${Date.now()}.txt`
    );
  }

  async function deleteRecord(recordId) {
    if (authUser) {
      await supabase
        .from("session_records")
        .delete()
        .eq("id", recordId)
        .eq("user_id", authUser.id);
    }

    setRecords(records.filter((record) => record.id !== recordId));
  }

  async function clearHistory() {
    if (authUser) {
      await supabase
        .from("session_records")
        .delete()
        .eq("user_id", authUser.id);
    }

    setRecords([]);
  }

  function WelcomeScreen() {
    return (
      <main className="min-h-screen bg-[#F8EFE3] text-[#2C241D]">
        <section className="mx-auto flex min-h-screen max-w-md flex-col items-center justify-center px-3 py-4">
          <div className="relative w-full overflow-hidden rounded-[2.5rem] bg-white shadow-2xl">
            <img
              src="/koda-cover.png"
              alt="Koda portada"
              className="pointer-events-none block w-full select-none"
              draggable="false"
            />

            <div className="absolute right-[7%] top-[4%] z-30 flex gap-2 rounded-2xl bg-white/85 p-2 shadow-lg backdrop-blur-sm">
              <button
                type="button"
                onClick={() => handleLanguageChange("es")}
                className={`rounded-xl px-3 py-2 text-sm font-black ${
                  language === "es"
                    ? "bg-[#2C241D] text-white"
                    : "bg-[#FFF1DC] text-[#2C241D]"
                }`}
              >
                ES
              </button>

              <button
                type="button"
                onClick={() => handleLanguageChange("en")}
                className={`rounded-xl px-3 py-2 text-sm font-black ${
                  language === "en"
                    ? "bg-[#2C241D] text-white"
                    : "bg-[#FFF1DC] text-[#2C241D]"
                }`}
              >
                EN
              </button>
            </div>

            <button
              type="button"
              onClick={() => {
                setAuthMode("signup");
                setLastSavedMessage("");
                setScreen("register");
              }}
              className="absolute left-[16%] top-[68.5%] z-30 flex h-[7.5%] w-[68%] items-center justify-center rounded-[2rem] bg-[#B57B2B] px-3 text-center text-base font-black text-white shadow-xl transition hover:bg-[#9E6A22] active:scale-[0.98]"
            >
              {t.start} ✨
            </button>

            <button
              type="button"
              onClick={() => {
                setAuthMode("login");
                setLastSavedMessage("");
                setScreen("register");
              }}
              className="absolute left-[16%] top-[77.2%] z-30 flex h-[7.5%] w-[68%] items-center justify-center rounded-[2rem] border border-[#E1C9AB] bg-white/90 px-3 text-center text-base font-black text-[#5C4A3F] shadow-lg transition hover:bg-white active:scale-[0.98]"
            >
              {t.login}
            </button>
          </div>
        </section>
      </main>
    );
  }

  function RegisterScreen() {
    const isLogin = authMode === "login";

    return (
      <main className="min-h-screen bg-gradient-to-br from-[#FFF8EE] via-[#F7EFE4] to-[#F2E4D5] px-4 py-6 text-[#2C241D]">
        <section className="mx-auto max-w-3xl">
          <button
            type="button"
            onClick={() => setScreen("welcome")}
            className="mb-5 rounded-2xl bg-white/80 px-4 py-3 font-bold shadow"
          >
            {t.back}
          </button>

          <div className="rounded-[2.5rem] bg-white/85 p-6 shadow-2xl md:p-8">
            <div className="mb-6 flex items-center gap-4">
              <div className="grid h-20 w-20 place-items-center rounded-3xl bg-[#FFF1DC] text-5xl">
                🧸
              </div>

              <div>
                <h1 className="text-3xl font-black md:text-5xl">
                  {isLogin ? t.loginTitle : t.registerTitle}
                </h1>
                <p className="mt-2 text-[#6E6258]">
                  {isLogin ? t.loginSubtitle : t.registerSubtitle}
                </p>
              </div>
            </div>

            <div className="grid gap-4 md:grid-cols-2">
              {!isLogin && (
                <label className="md:col-span-2">
                  <span className="mb-2 block text-sm font-bold text-[#6E6258]">
                    {t.fullName}
                  </span>
                  <input
                    value={professionalProfile.name}
                    onChange={(event) =>
                      setProfessionalProfile((current) => ({
                        ...current,
                        name: event.target.value,
                      }))
                    }
                    className="w-full rounded-2xl border border-[#E7D8C5] bg-white px-4 py-3 outline-none focus:border-[#C58E55]"
                  />
                </label>
              )}

              <label>
                <span className="mb-2 block text-sm font-bold text-[#6E6258]">
                  {t.email}
                </span>
                <input
                  type="email"
                  value={professionalProfile.email}
                  onChange={(event) =>
                    setProfessionalProfile((current) => ({
                      ...current,
                      email: event.target.value,
                    }))
                  }
                  className="w-full rounded-2xl border border-[#E7D8C5] bg-white px-4 py-3 outline-none focus:border-[#C58E55]"
                />
              </label>

              <label>
                <span className="mb-2 block text-sm font-bold text-[#6E6258]">
                  {t.password}
                </span>
                <input
                  type="password"
                  value={password}
                  onChange={(event) => setPassword(event.target.value)}
                  className="w-full rounded-2xl border border-[#E7D8C5] bg-white px-4 py-3 outline-none focus:border-[#C58E55]"
                />
              </label>

              {!isLogin && (
                <>
                  <label>
                    <span className="mb-2 block text-sm font-bold text-[#6E6258]">
                      {t.specialty}
                    </span>
                    <input
                      value={professionalProfile.specialty}
                      onChange={(event) =>
                        setProfessionalProfile((current) => ({
                          ...current,
                          specialty: event.target.value,
                        }))
                      }
                      placeholder="Psicología infantil / Terapia de lenguaje..."
                      className="w-full rounded-2xl border border-[#E7D8C5] bg-white px-4 py-3 outline-none focus:border-[#C58E55]"
                    />
                  </label>

                  <label>
                    <span className="mb-2 block text-sm font-bold text-[#6E6258]">
                      {t.country}
                    </span>
                    <input
                      value={professionalProfile.country}
                      onChange={(event) =>
                        setProfessionalProfile((current) => ({
                          ...current,
                          country: event.target.value,
                        }))
                      }
                      className="w-full rounded-2xl border border-[#E7D8C5] bg-white px-4 py-3 outline-none focus:border-[#C58E55]"
                    />
                  </label>

                  <label>
                    <span className="mb-2 block text-sm font-bold text-[#6E6258]">
                      {t.practiceType}
                    </span>
                    <input
                      value={professionalProfile.practiceType}
                      onChange={(event) =>
                        setProfessionalProfile((current) => ({
                          ...current,
                          practiceType: event.target.value,
                        }))
                      }
                      placeholder="Consulta privada / Clínica / Escuela..."
                      className="w-full rounded-2xl border border-[#E7D8C5] bg-white px-4 py-3 outline-none focus:border-[#C58E55]"
                    />
                  </label>

                  <label>
                    <span className="mb-2 block text-sm font-bold text-[#6E6258]">
                      {t.preferredLanguage}
                    </span>
                    <select
                      value={language}
                      onChange={(event) =>
                        handleLanguageChange(event.target.value)
                      }
                      className="w-full rounded-2xl border border-[#E7D8C5] bg-white px-4 py-3 outline-none focus:border-[#C58E55]"
                    >
                      <option value="es">Español</option>
                      <option value="en">English</option>
                    </select>
                  </label>
                </>
              )}
            </div>

            {lastSavedMessage && (
              <p className="mt-5 rounded-2xl bg-[#FFF1DC] px-4 py-3 font-bold text-[#6E4F36]">
                {lastSavedMessage}
              </p>
            )}

            <button
              type="button"
              onClick={isLogin ? loginProfessional : saveProfessionalProfile}
              className="mt-6 w-full rounded-[2rem] bg-[#2C241D] px-6 py-4 text-lg font-black text-white shadow-xl hover:bg-[#46382C]"
            >
              {isLogin ? t.loginButton : t.saveProfile}
            </button>

            <button
              type="button"
              onClick={() => {
                setAuthMode(isLogin ? "signup" : "login");
                setLastSavedMessage("");
              }}
              className="mt-4 w-full rounded-[2rem] border border-[#E1C9AB] bg-white px-6 py-4 text-lg font-black text-[#5C4A3F] shadow-lg hover:bg-[#FFF8EE]"
            >
              {isLogin ? t.needCreateProfile : t.alreadyHaveProfile}
            </button>
          </div>
        </section>
      </main>
    );
  }

  function DashboardScreen() {
    return (
      <main className="min-h-screen bg-gradient-to-br from-[#FFF8EE] via-[#F7EFE4] to-[#F2E4D5] px-4 py-6 text-[#2C241D]">
        <section className="mx-auto max-w-5xl">
          <div className="mb-6 flex items-center justify-between gap-4">
            <div>
              <div className="mb-2 inline-flex rounded-full bg-white/80 px-4 py-2 text-sm font-bold shadow">
                🧸 Koda
              </div>

              <h1 className="text-4xl font-black md:text-6xl">
                {t.dashboardTitle}
              </h1>

              <p className="mt-2 max-w-2xl text-lg text-[#6E6258]">
                {t.dashboardSubtitle}
              </p>
            </div>

            <button
              type="button"
              onClick={() => setScreen("welcome")}
              className="rounded-2xl bg-white/80 px-4 py-3 font-bold shadow"
            >
              {t.back}
            </button>
          </div>

          <div className="mb-5 rounded-[2rem] bg-white/80 p-5 shadow-xl">
            <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
              <div>
                <p className="text-sm font-bold text-[#6E6258]">
                  {t.profileTitle}
                </p>
                <h2 className="text-2xl font-black">
                  {professionalProfile.name || "Profesional Koda"}
                </h2>
                <p className="text-[#6E6258]">
                  {professionalProfile.specialty || "Especialidad pendiente"} ·{" "}
                  {professionalProfile.email || "Correo pendiente"}
                </p>
              </div>

              <div className="flex flex-wrap gap-3">
                <button
                  type="button"
                  onClick={() => {
                    setAuthMode("signup");
                    setScreen("register");
                  }}
                  className="rounded-2xl bg-[#FFF1DC] px-4 py-3 font-black"
                >
                  {t.updateProfile}
                </button>

                <button
                  type="button"
                  onClick={signOutProfessional}
                  className="rounded-2xl bg-white px-4 py-3 font-black shadow"
                >
                  {t.signOut}
                </button>
              </div>
            </div>
          </div>

          <div className="grid gap-5 md:grid-cols-3">
            <button
              type="button"
              onClick={() => setScreen("engine")}
              className="rounded-[2rem] bg-[#2C241D] p-6 text-left text-white shadow-xl transition hover:scale-[1.01]"
            >
              <div className="text-5xl">✨</div>
              <h2 className="mt-5 text-2xl font-black">{t.newSession}</h2>
              <p className="mt-2 text-white/70">{t.continueSession}</p>
            </button>

            <button
              type="button"
              onClick={() => setScreen("history")}
              className="rounded-[2rem] bg-white/80 p-6 text-left shadow-xl transition hover:scale-[1.01]"
            >
              <div className="text-5xl">📁</div>
              <h2 className="mt-5 text-2xl font-black">{t.savedRecords}</h2>
              <p className="mt-2 text-[#6E6258]">
                {records.length} registros
              </p>
            </button>

            <div className="rounded-[2rem] bg-[#F7E7D1] p-6 shadow-xl">
              <div className="text-4xl">🛡️</div>
              <h2 className="mt-5 text-xl font-black">Koda Light</h2>
              <p className="mt-2 text-[#6E4F36]">{t.exportInfo}</p>
            </div>
          </div>
        </section>
      </main>
    );
  }

  function EngineScreen() {
    return (
      <main className="min-h-screen bg-gradient-to-br from-[#FFF8EE] via-[#F7EFE4] to-[#F2E4D5] px-4 py-6 text-[#2C241D]">
        <section className="mx-auto max-w-6xl">
          <div className="mb-6 flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
            <div>
              <div className="mb-3 inline-flex rounded-full bg-white/75 px-4 py-2 text-sm font-semibold shadow-sm">
                🧸 Koda MVP Engine
              </div>

              <h1 className="text-5xl font-black tracking-tight md:text-7xl">
                Koda
              </h1>

              <p className="mt-2 max-w-2xl text-lg text-[#6E6258]">
                {t.appSubtitle}
              </p>

              <p className="mt-3 inline-flex rounded-full bg-[#2C241D] px-4 py-2 text-sm font-semibold text-white">
                ✨ {t.demoMode}
              </p>
            </div>

            <div className="flex flex-col gap-3 rounded-3xl bg-white/85 p-4 shadow-xl">
              <button
                type="button"
                onClick={() => setScreen("dashboard")}
                className="rounded-2xl border border-[#E1C9AB] px-4 py-2 font-bold"
              >
                {t.back}
              </button>

              <div>
                <label className="mb-2 block text-sm font-bold">
                  {t.language}
                </label>

                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={() => handleLanguageChange("es")}
                    className={`rounded-2xl px-4 py-2 font-bold ${
                      language === "es"
                        ? "bg-[#2C241D] text-white"
                        : "bg-[#FFF1DC]"
                    }`}
                  >
                    Español
                  </button>

                  <button
                    type="button"
                    onClick={() => handleLanguageChange("en")}
                    className={`rounded-2xl px-4 py-2 font-bold ${
                      language === "en"
                        ? "bg-[#2C241D] text-white"
                        : "bg-[#FFF1DC]"
                    }`}
                  >
                    English
                  </button>
                </div>
              </div>
            </div>
          </div>

          <div className="grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">
            <div className="rounded-[2rem] bg-white/85 p-6 shadow-xl">
              <h2 className="mb-5 text-2xl font-black">🧒 {t.quick}</h2>

              <div className="grid gap-4 md:grid-cols-2">
                <label>
                  <span className="mb-2 block text-sm font-semibold text-[#6E6258]">
                    {t.childName}
                  </span>

                  <input
                    value={childName}
                    onChange={(event) => setChildName(event.target.value)}
                    className="w-full rounded-2xl border border-[#E7D8C5] bg-white px-4 py-3 outline-none focus:border-[#C58E55]"
                  />
                </label>

                <label>
                  <span className="mb-2 block text-sm font-semibold text-[#6E6258]">
                    {t.age}
                  </span>

                  <input
                    value={age}
                    onChange={(event) => setAge(event.target.value)}
                    className="w-full rounded-2xl border border-[#E7D8C5] bg-white px-4 py-3 outline-none focus:border-[#C58E55]"
                  />
                </label>
              </div>

              <div className="mt-5">
                <span className="mb-2 block text-sm font-semibold text-[#6E6258]">
                  {t.character}
                </span>

                <div className="grid gap-3 md:grid-cols-3">
                  {characterOptions.map((option) => (
                    <button
                      type="button"
                      key={option.id}
                      onClick={() => setCharacterId(option.id)}
                      className={`rounded-2xl border px-3 py-4 text-left transition ${
                        characterId === option.id
                          ? "border-[#C58E55] bg-[#FFF1DC] shadow-md"
                          : "border-[#E7D8C5] bg-white hover:bg-[#FFF8EE]"
                      }`}
                    >
                      <div className="text-3xl">{option.emoji}</div>

                      <div className="mt-2 text-sm font-bold">
                        {language === "es" ? option.es : option.en}
                      </div>
                    </button>
                  ))}
                </div>
              </div>

              <label className="mt-5 block">
                <span className="mb-2 block text-sm font-semibold text-[#6E6258]">
                  {t.intention}
                </span>

                <select
                  value={intention}
                  onChange={(event) => setIntention(event.target.value)}
                  className="w-full rounded-2xl border border-[#E7D8C5] bg-white px-4 py-3 outline-none focus:border-[#C58E55]"
                >
                  {intentions[language].map((item) => (
                    <option key={item}>{item}</option>
                  ))}
                </select>
              </label>

              <label className="mt-5 block">
                <span className="mb-2 block text-sm font-semibold text-[#6E6258]">
                  {t.notes}
                </span>

                <textarea
                  value={sessionNotes}
                  onChange={(event) => setSessionNotes(event.target.value)}
                  className="min-h-24 w-full resize-none rounded-3xl border border-[#E7D8C5] bg-white px-5 py-4 text-base outline-none focus:border-[#C58E55]"
                  placeholder={t.notesPlaceholder}
                />
              </label>

              <div className="mt-5 rounded-3xl bg-[#F7E7D1] p-4 text-sm leading-relaxed text-[#6E4F36]">
                🛡️ {t.safety}
              </div>
            </div>

            <div className="rounded-[2rem] bg-white/85 p-6 shadow-xl">
              <div className="mb-5 flex items-center justify-between gap-4">
                <h2 className="text-2xl font-black">✨ {t.engine}</h2>

                <div
                  className={`rounded-full px-3 py-1 text-sm font-bold ${
                    isSpeaking
                      ? "bg-green-100 text-green-700"
                      : isWorking
                      ? "bg-yellow-100 text-yellow-700"
                      : statusMessage === t.premiumPending
                      ? "bg-orange-100 text-orange-700"
                      : "bg-[#FFF1DC]"
                  }`}
                >
                  {statusMessage}
                </div>
              </div>

              <label>
                <span className="mb-2 block text-sm font-semibold text-[#6E6258]">
                  {t.therapistPhrase}
                </span>

                <textarea
                  value={therapistText}
                  onChange={(event) => setTherapistText(event.target.value)}
                  className="min-h-40 w-full resize-none rounded-3xl border border-[#E7D8C5] bg-white px-5 py-4 text-base outline-none focus:border-[#C58E55]"
                  placeholder={t.placeholder}
                />
              </label>

              <div className="mt-4 flex flex-col gap-3 sm:flex-row">
                <button
                  type="button"
                  onClick={handleTalkWithKoda}
                  disabled={isWorking || isSpeaking}
                  className="rounded-2xl bg-[#2C241D] px-5 py-3 font-bold text-white shadow-lg hover:bg-[#46382C] disabled:opacity-60"
                >
                  ✨ {t.talk}
                </button>

                {adaptedText &&
                  !adaptedText.startsWith("ERROR") &&
                  !adaptedText.startsWith("REAL ERROR") && (
                    <>
                      <button
                        type="button"
                        onClick={saveSessionRecord}
                        disabled={isWorking || isSpeaking}
                        className="rounded-2xl bg-[#B57B2B] px-5 py-3 font-bold text-white shadow-md hover:bg-[#9E6A22] disabled:opacity-60"
                      >
                        💾 {t.saveRecord}
                      </button>

                      <button
                        type="button"
                        onClick={copyCurrentSummary}
                        className="rounded-2xl bg-white px-5 py-3 font-bold text-[#2C241D] shadow-md"
                      >
                        📋 {t.copySummary}
                      </button>

                      <button
                        type="button"
                        onClick={downloadCurrentSummary}
                        className="rounded-2xl bg-white px-5 py-3 font-bold text-[#2C241D] shadow-md"
                      >
                        ⬇️ {t.downloadSummary}
                      </button>
                    </>
                  )}

                {(isWorking || isSpeaking) && (
                  <button
                    type="button"
                    onClick={stopAudio}
                    className="rounded-2xl border border-[#D8B489] px-5 py-3 font-bold"
                  >
                    {t.stop}
                  </button>
                )}
              </div>

              {lastSavedMessage && (
                <p className="mt-4 rounded-2xl bg-[#FFF1DC] px-4 py-3 font-bold text-[#6E4F36]">
                  {lastSavedMessage}
                </p>
              )}

              <div className="mt-5 rounded-[2rem] bg-[#2C241D] p-6 text-white shadow-inner">
                <div className="mb-4 flex items-center gap-4">
                  <div
                    className={`grid h-16 w-16 place-items-center rounded-3xl bg-white/15 text-4xl ${
                      isSpeaking ? "animate-pulse" : ""
                    }`}
                  >
                    {character.emoji}
                  </div>

                  <div>
                    <p className="text-sm text-white/60">{t.kodaWouldSay}</p>

                    <p className="text-lg font-bold">
                      {language === "es" ? character.es : character.en}
                    </p>
                  </div>
                </div>

                <p className="min-h-28 whitespace-pre-wrap text-xl leading-relaxed text-white/90">
                  {adaptedText || t.empty}
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
    );
  }

  function HistoryScreen() {
    return (
      <main className="min-h-screen bg-gradient-to-br from-[#FFF8EE] via-[#F7EFE4] to-[#F2E4D5] px-4 py-6 text-[#2C241D]">
        <section className="mx-auto max-w-5xl">
          <div className="mb-6 flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
            <div>
              <div className="mb-2 inline-flex rounded-full bg-white/80 px-4 py-2 text-sm font-bold shadow">
                📁 Koda
              </div>

              <h1 className="text-4xl font-black md:text-6xl">
                {t.savedRecords}
              </h1>

              <p className="mt-2 max-w-2xl text-lg text-[#6E6258]">
                {t.exportInfo}
              </p>
            </div>

            <div className="flex gap-3">
              {records.length > 0 && (
                <button
                  type="button"
                  onClick={clearHistory}
                  className="rounded-2xl bg-red-100 px-4 py-3 font-bold text-red-700 shadow"
                >
                  {t.clearHistory}
                </button>
              )}

              <button
                type="button"
                onClick={() => setScreen("dashboard")}
                className="rounded-2xl bg-white/80 px-4 py-3 font-bold shadow"
              >
                {t.back}
              </button>
            </div>
          </div>

          {records.length === 0 ? (
            <div className="rounded-[2rem] bg-white/85 p-8 text-center shadow-xl">
              <div className="text-6xl">📁</div>
              <h2 className="mt-4 text-2xl font-black">{t.historyEmpty}</h2>
            </div>
          ) : (
            <div className="space-y-4">
              {records.map((record) => (
                <div
                  key={record.id}
                  className="rounded-[2rem] bg-white/85 p-5 shadow-xl"
                >
                  <div className="mb-4 flex flex-col gap-3 md:flex-row md:items-start md:justify-between">
                    <div>
                      <h2 className="text-2xl font-black">
                        {record.childName || "Koda"} · {record.age || "N/A"}
                      </h2>
                      <p className="text-sm font-bold text-[#6E6258]">
                        {record.dateLabel} · {record.intention}
                      </p>
                    </div>

                    <div className="flex flex-wrap gap-2">
                      <button
                        type="button"
                        onClick={() =>
                          copyText(
                            formatRecord(
                              {
                                ...record,
                                professionalName: professionalProfile.name,
                              },
                              language
                            )
                          )
                        }
                        className="rounded-2xl bg-[#FFF1DC] px-4 py-2 font-bold"
                      >
                        📋 {t.copySummary}
                      </button>

                      <button
                        type="button"
                        onClick={() =>
                          downloadTextFile(
                            formatRecord(
                              {
                                ...record,
                                professionalName: professionalProfile.name,
                              },
                              language
                            ),
                            `koda-registro-${record.id}.txt`
                          )
                        }
                        className="rounded-2xl bg-[#2C241D] px-4 py-2 font-bold text-white"
                      >
                        ⬇️ {t.downloadSummary}
                      </button>

                      <button
                        type="button"
                        onClick={() => deleteRecord(record.id)}
                        className="rounded-2xl bg-red-100 px-4 py-2 font-bold text-red-700"
                      >
                        {t.deleteRecord}
                      </button>
                    </div>
                  </div>

                  <div className="grid gap-4 md:grid-cols-2">
                    <div className="rounded-3xl bg-[#FFF8EE] p-4">
                      <p className="mb-2 text-sm font-black text-[#6E6258]">
                        {t.therapistPhrase}
                      </p>
                      <p className="leading-relaxed">{record.therapistText}</p>
                    </div>

                    <div className="rounded-3xl bg-[#2C241D] p-4 text-white">
                      <p className="mb-2 text-sm font-black text-white/60">
                        {t.kodaWouldSay}
                      </p>
                      <p className="leading-relaxed">{record.adaptedText}</p>
                    </div>
                  </div>

                  {record.notes && (
                    <div className="mt-4 rounded-3xl bg-[#F7E7D1] p-4">
                      <p className="mb-2 text-sm font-black text-[#6E6258]">
                        {t.notes}
                      </p>
                      <p>{record.notes}</p>
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </section>
      </main>
    );
  }

  if (isAuthLoading) {
    return (
      <main className="grid min-h-screen place-items-center bg-[#F8EFE3] text-[#2C241D]">
        <div className="rounded-[2rem] bg-white/85 p-8 text-center shadow-xl">
          <div className="text-5xl">🧸</div>
          <p className="mt-4 text-xl font-black">{t.loading}</p>
        </div>
      </main>
    );
  }

  if (screen === "welcome") return <WelcomeScreen />;
  if (screen === "register") return <RegisterScreen />;
  if (screen === "dashboard") return <DashboardScreen />;
  if (screen === "history") return <HistoryScreen />;
  return <EngineScreen />;
}